name: InSecurITy
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: Peace Of Mind In An InSecure World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#00b9f1'
    - '#818284'
    - '#005c8d'
  brandStrength: 0.125
  lightness: 0.5673141123261303
  saturation: 0.5544477943331003
  rhythmicContrast: 0.7698409869335592
purpose: []
